version: "3.9"

services:

  web-app:
    container_name: dp_web
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/opt/digitalplatform
      - ./src/static:/opt/digitalplatform/static
      - ../data:/opt/data
    command: >
      sh -c "python manage.py collectstatic --no-input && python manage.py migrate && python manage.py loaddata core/fixtures/*.* && python manage.py runserver 0.0.0.0:8000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - db
      - redis

  db:
    image: postgres:16.2-alpine
    container_name: dp_psql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./docker_compose_volumes/pg_data/:/var/lib/postgresql/data

  redis:
      image: redis:alpine
      container_name: dp_redis
      volumes:
        - ./docker_compose_volumes/redis:/root/redis
        - ./docker_compose_volumes/redis/redis.conf:/usr/local/etc/redis/redis.conf
      environment:
        - REDIS_PASSWORD=${REDIS_PASSWORD}
        - REDIS_PORT=${REDIS_PORT}
      ports:
        - "6379:6379"

  nginx:
    image: 1.25.5-alpine
    container_name: dp_nginx
    build:
      context: ./docker_compose_volumes/nginx
    ports:
      - "80:80"
    depends_on:
      - web-app