# Generated by Django 5.0.1 on 2024-02-08 19:36

from phonenumber_field.modelfields import PhoneNumberField
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.TextField(default='Цифровая платформа', max_length=200,
                                               verbose_name='Полное название сайта')),
                ('short_site_name', models.CharField(verbose_name='Краткое название сайта', max_length=31)),
                ('description', models.TextField(verbose_name='Описание главной страницы')),
                ('logotype', models.ImageField(upload_to='img', verbose_name='Логотип', blank=True, null=True)),
                ('contact_description', models.TextField(blank=True, max_length=200, null=True,
                                                         verbose_name='Об организации')),
                ('phone', PhoneNumberField(blank=True, help_text='Например: +999999999', max_length=128, null=True,
                                           region='', verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, help_text='Пример: example@mail.ru', max_length=254, null=True,
                                            verbose_name='Электронная почта')),
                ('address', models.CharField(blank=True, help_text='Пример: 129344, г. Москва, Проспект мира д.1',
                                             max_length=100, null=True, verbose_name='Адрес')),
                ('vk_link', models.URLField(blank=True, null=True, verbose_name='Вконтакте')),
                ('youtube_link', models.URLField(blank=True, null=True, verbose_name='YouTube')),
                ('odnoklassniki_link', models.URLField(blank=True, null=True, verbose_name='Одноклассники')),
                ('dzen_link', models.URLField(blank=True, null=True, verbose_name='Дзен')),
                ('telegram_link', models.URLField(blank=True, null=True, verbose_name='Telegram')),
                ('whatsapp_link', models.URLField(blank=True, null=True, verbose_name='WhatsApp')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
