# Generated by Django 5.0 on 2023-12-30 08:31

from django.db import migrations
from college.models import CustomPerson


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    def generate_superuser(apps, schema_editor):

        superuser = CustomPerson.objects.create_superuser(
            username='admin',
            first_name='Admin',
            last_name='DigitalPlatform',
            email='kafomin@yandex.ru',
            password='Pa$$w0rd')

        superuser.save()

    def generate_default_teacher(apps, schema_editor):

        teacher = CustomPerson.objects.create_user(
            username='none',
            first_name='none',
            last_name='none',
            middle_name='none',
            email='kafomin@yandex.ru',
            password='Gh3g0l@dfntkmgjEvjkX@yb$')

        teacher.save()

    operations = [
        migrations.RunPython(generate_superuser),
        migrations.RunPython(generate_default_teacher),
    ]
