# Generated by Django 5.0.1 on 2024-02-08 19:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_create_default_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Цифровая платформа', max_length=256, verbose_name='Полное название сайта')),
                ('short_site_name', models.CharField(verbose_name='Краткое название сайта', max_length=19, help_text='Например, одним словом')),
                ('description', models.TextField(verbose_name='Описание главной страницы')),
                ('logotype', models.ImageField(upload_to='site/img', verbose_name='Логотип', blank=True, null=True)),
                ('contact_description', models.CharField(blank=True, help_text='Дополнительная контактная информация. Отображается под заголовком.', max_length=100, null=True, verbose_name='Контактная информация')),
                ('phone', models.CharField(blank=True, help_text='Номер телефона в формате: +999999999', max_length=17, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, help_text='Пример: example@mail.ru', max_length=254, null=True, verbose_name='Электронная почта')),
                ('address', models.CharField(blank=True, help_text='Пример: 129344, г. Москва, Проспект мира д.1', max_length=100, null=True, verbose_name='Адрес')),
                ('vk_link', models.URLField(blank=True, null=True, verbose_name='Вконтакте')),
                ('youtube_link', models.URLField(blank=True, null=True, verbose_name='YouTube')),
                ('odnoklassniki_link', models.URLField(blank=True, null=True, verbose_name='Одноклассники')),
                ('dzen_link', models.URLField(blank=True, null=True, verbose_name='Дзен')),
                ('telegram_link', models.URLField(blank=True, null=True, verbose_name='Telegram')),
                ('whatsapp_link', models.URLField(blank=True, null=True, verbose_name='WhatsApp')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
