# Generated by Django 5.0.1 on 2024-02-08 20:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Полоное наименование', max_length=200, verbose_name='Наименование')),
                ('short_name', models.CharField(help_text='Сокращенное название', max_length=50, verbose_name='Сокращение')),
                ('phone', models.CharField(blank=True, help_text='Введите номер телефона в формате: +999999999', max_length=17, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон')),
                ('coordinate', models.CharField(blank=True, help_text='Введите адрес расположения площадки', max_length=500, verbose_name='Адрес')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Руководитель')),
            ],
            options={
                'verbose_name': 'Площадка',
                'verbose_name_plural': 'Площадки',
                'ordering': ('short_name',),
            },
        ),
    ]
