# Generated by Django 5.0.1 on 2024-02-25 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_userservicescategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например, СДО Академия', max_length=25, unique=True, verbose_name='Название')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('icon', models.CharField(help_text='Используйте Fontawesome', max_length=50, verbose_name='Иконка')),
                ('visible', models.BooleanField(default=True, verbose_name='Видимость')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usrsrv_cat_to_usrsrvcat_id_fkey', to='college.userservicescategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Пользовательский сервис',
                'verbose_name_plural': 'Пользовательские сервисы',
            },
        ),
    ]
