# Generated by Django 5.0.1 on 2024-02-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Пример:"1 поток","2 поток"', max_length=30, verbose_name='Наименование потока')),
            ],
            options={
                'verbose_name': 'Распределение групп потоков - обозначения',
                'verbose_name_plural': 'Распределение групп потоков - обозначения',
                'ordering': ('number',),
            },
        ),
    ]
