# Generated by Django 5.0.1 on 2024-02-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_dayweek'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleCalendarMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
                ('symbol', models.CharField(blank=True, unique=True, help_text='Символ отображаемый в графике', max_length=5, null=True, verbose_name='Символ')),
            ],
            options={'ordering': ('name',), 'verbose_name': 'График учебного процесса - обозначения', 'verbose_name_plural': 'График учебного процесса - обозначения'},
        ),
    ]
