# Generated by Django 5.0.1 on 2024-02-16 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationpart', '0003_studygroup'),
        ('schedule', '0006_schedulecalendarmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_week', models.DateField(verbose_name='Начало учебной недели')),
                ('end_week', models.DateField(verbose_name='Конец учебной недели')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schcal_group_to_studygroup_id_fkey', to='educationpart.studygroup', verbose_name='Группа')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schcal_mark_to_schcalmark_id_fkey', to='schedule.schedulecalendarmark', verbose_name='Отметка')),
            ],
            options={
                'verbose_name': 'График учебного процесса',
                'verbose_name_plural': 'График учебного процесса',
            },
        ),
    ]
