# Generated by Django 5.0.1 on 2024-02-16 08:46

from django.db import migrations
from schedule.models import DayWeek, NumberWeek


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_dayweek'),
        ('schedule', '0004_numberweek'),
    ]

    def create_day_number(apps, schema_editor):

        odd_week = NumberWeek.objects.get(name='Нечетная')
        even_week = NumberWeek.objects.get(name='Четная')

        objs = DayWeek.objects.bulk_create(
            [
                DayWeek(id=1, name='Понедельник', week_id=odd_week.id),
                DayWeek(id=2, name='Вторник', week_id=odd_week.id),
                DayWeek(id=3, name='Среда', week_id=odd_week.id),
                DayWeek(id=4, name='Четверг', week_id=odd_week.id),
                DayWeek(id=5, name='Пятница', week_id=odd_week.id),
                DayWeek(id=6, name='Суббота', week_id=odd_week.id),
                DayWeek(id=7, name='Воскресенье', week_id=odd_week.id),
                DayWeek(id=8, name='Понедельник', week_id=even_week.id),
                DayWeek(id=9, name='Вторник', week_id=even_week.id),
                DayWeek(id=10, name='Среда', week_id=even_week.id),
                DayWeek(id=11, name='Четверг', week_id=even_week.id),
                DayWeek(id=12, name='Пятница', week_id=even_week.id),
                DayWeek(id=13, name='Суббота', week_id=even_week.id),
                DayWeek(id=14, name='Воскресенье', week_id=even_week.id)
            ]
        )

    operations = [migrations.RunPython(create_day_number),]
