# Generated by Django 5.0.1 on 2024-02-17 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_auditory'),
        ('educationpart', '0003_studygroup'),
        ('schedule', '0007_schedulecalendar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auditory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                               related_name='sched_auditory_to_auditory_id_fkey', to='college.auditory',
                                               verbose_name='Аудитория')),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                             related_name='sched_couple_to_couple_id_fkey', to='schedule.couple',
                                             verbose_name='Номер пары')),
                ('dayweek', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                              related_name='sched_weekday_to_weekday_id_fkey', to='schedule.dayweek',
                                              verbose_name='День недели')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                                 related_name='sched_discipline_to_discipline_id_fkey',
                                                 to='educationpart.discipline', verbose_name='Дисциплина')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                            related_name='sched_studygroup_to_studygroup_id_fkey',
                                            to='educationpart.studygroup', verbose_name='Группа')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                              related_name='sched_teacher_to_customperson_id_fkey',
                                              to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
                'ordering': ('couple',),
            },
        ),
    ]
