# Generated by Django 5.0.1 on 2024-02-16 10:42

from django.db import migrations, models
from schedule.models import ScheduleCalendarMark


class Migration(migrations.Migration):

    dependencies = [('schedule', '0008_schedulecalendarmark'),]

    def create_default_schedule_calendar_mark(apps, schema_editor):

        obj = ScheduleCalendarMark.objects.bulk_create(
            [
                ScheduleCalendarMark(name='Теоретическое обучение', symbol=''),
                ScheduleCalendarMark(name='Учебная практика', symbol='0'),
                ScheduleCalendarMark(name='Производственная практика (по профилю специальности)', symbol='8'),
                ScheduleCalendarMark(name='Производственная практика (преддипломная)', symbol='X'),
                ScheduleCalendarMark(name='Промежуточная аттестация', symbol='::'),
                ScheduleCalendarMark(name='Государственная (итоговая) аттестация', symbol='III'),
                ScheduleCalendarMark(name='Подготовка к государственной итоговой аттестации', symbol='A'),
                ScheduleCalendarMark(name='Каникулы', symbol='==')
            ]
        )

    operations = [migrations.RunPython(create_default_schedule_calendar_mark), ]
