# Generated by Django 5.0.1 on 2024-02-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_uploadschedulechange'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
