upstream web_app {
    server app:8000;
}

server {

    listen 80;
    charset utf-8;

    location / {
        proxy_pass http://web_app/;
        proxy_set_header Host $host:8000;  # в pre-prod указываем путь
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_redirect off;
        proxy_set_header X-Forwarded-Host $server_name;
        proxy_read_timeout 1200s;
    }


    location /s/ {
        alias /opt/staticfiles/;
    }

    location /m/ {
        alias /opt/mediafiles/;
    }

}
