"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import environ
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from the .env file
# https://github.com/joke2k/django-environ

env = environ.Env(DEBUG=(bool, False))
environ.Env.read_env(os.path.join(BASE_DIR, '../.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = env('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = env('DEBUG')

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

INTERNAL_IPS = ['127.0.0.1']

# SECURITY Deploy on in production
# https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/#critical-settings

CSRF_COOKIE_SECURE = env('CSRF_COOKIE_SECURE', default=False)

SESSION_COOKIE_SECURE = env('SESSION_COOKIE_SECURE', default=False)

SECURE_SSL_REDIRECT = env('SECURE_SSL_REDIRECT', default=False)

SECURE_HSTS_SECONDS = env('SECURE_HSTS_SECONDS', default=False)

SECURE_HSTS_INCLUDE_SUBDOMAINS = env('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=False)

SECURE_HSTS_PRELOAD = env('SECURE_HSTS_PRELOAD', default=False)

# Admins
# https://docs.djangoproject.com/en/5.0/ref/settings/#std-setting-ADMINS

ADMINS = [("Kirill Kuznetsov", "kafomin@yandex.ru")]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',

    'ckeditor',
    'ckeditor_uploader',
    'debug_toolbar',
    # https://github.com/silentsokolov/django-admin-rangefilter
    'rangefilter',
    # https://github.com/mrts/django-admin-list-filter-dropdown?ysclid=ltxamzeduk363659490
    'django_admin_listfilter_dropdown',
    'django_celery_results',

    # modules
    'schedule_parsing.apps.ScheduleParsingConfig',
    'college.apps.CollegeConfig',
    'educationpart.apps.EducationpartConfig',
    'schedule.apps.ScheduleConfig',
    'reference.apps.ReferenceConfig',
    'docs.apps.DocsConfig',

    'phonenumber_field',
    'django_cleanup.apps.CleanupConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'core.urls'

# Templates
# https://docs.djangoproject.com/en/5.0/topics/templates/

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'college.context_processors.load_settings',
                'college.context_processors.departments',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
# Important: use Postgresql in debug mode

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('POSTGRES_DB'),
        'USER': env('POSTGRES_USER'),
        'PASSWORD': env('POSTGRES_PASSWORD'),
        'HOST': env('POSTGRES_HOST'),
        'PORT': env('POSTGRES_PORT')
    }
}


# Fixtures
# https://docs.djangoproject.com/en/5.0/howto/initial-data/

FIXTURE_DIRS = []


# Auth
# https://docs.djangoproject.com/en/5.0/topics/auth/customizing/

AUTH_USER_MODEL = 'college.CustomPerson'

LOGIN_REDIRECT_URL = '/'

LOGOUT_REDIRECT_URL = '/'


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR / 'static'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'core/static'),
]


# MEDIA Files
# https://docs.djangoproject.com/en/5.0/ref/settings/#media-root

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, '../data/')


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Email Server
# https://docs.djangoproject.com/en/5.0/ref/settings/#std-setting-EMAIL_BACKEND
# https://www.abstractapi.com/guides/django-send-email

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = env('EMAIL_HOST', default='')
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
EMAIL_PORT = env('EMAIL_PORT', default='')
EMAIL_USE_TLS = env('EMAIL_USE_TLS', default=1)
EMAIL_USE_SSL = env('EMAIL_USE_SSL', default=0)


# CKEditor
# https://django-ckeditor.readthedocs.io/en/latest/#installation

# TODO: изменить путь сохранения файлов для разных типов
CKEDITOR_UPLOAD_PATH = 'ckeditor/'

# TODO: Скрываем предупреждение о CKEditor 4.22.1, проверить обновление в будущем
SILENCED_SYSTEM_CHECKS = ['ckeditor.W001']


# REDIS
# https://redis.io
# https://timeweb.cloud/tutorials/redis/ustanovka-i-nastrojka-redis-dlya-raznyh-os

REDIS_HOST = env('REDIS_HOST')

REDIS_USER = env('REDIS_USER')

REDIS_PASSWORD = env('REDIS_PASSWORD')

REDIS_PORT = env('REDIS_PORT')


# CELERY
# https://docs.celeryq.dev/en/latest/index.html
# RUN command: celery -A core worker -l INFO

CELERY_BROKER_URL = (f'redis://{REDIS_USER}:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/0', 'redis://redis:6378/0')

CELERY_BROKER_TRANSPORT_OPTIONS = {'visibility_timeout': 10}

CELERY_ACCEPT_CONTENT = ['application/json']

CELERY_TASK_SERIALIZER = 'json'

CELERY_RESULT_SERIALIZER = 'json'

CELERY_TIMEZONE = TIME_ZONE

CELERY_TASK_TRACK_STARTED = True

CELERY_RESULT_BACKEND = 'django-db'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': f'redis://{REDIS_USER}:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/1',
    }
}

CELERY_CACHE_BACKEND = 'default'
