# Generated by Django 5.0 on 2023-12-30 08:31

from django.db import migrations
from reference.models import Status


class Migration(migrations.Migration):

    dependencies = [('reference', '0001_initial'),]

    def generate_status(apps, schema_editor):

        objs = Status.objects.bulk_create(
            [
                Status(name='Создан'),
                Status(name='Принят'),
                Status(name='В работе'),
                Status(name='Готово к выдаче'),
                Status(name='Завершен'),
                Status(name='Отменено')
            ]
        )

    operations = [migrations.RunPython(generate_status),]
