# Generated by Django 5.0.1 on 2024-02-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_create_default_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
                ('example', models.FileField(upload_to='reference/example', verbose_name='Образец справки')),
            ],
            options={
                'verbose_name': 'Тип справки',
                'verbose_name_plural': 'Типы справок',
            },
        ),
    ]
