# Generated by Django 5.0.1 on 2024-02-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_auditory'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserServicesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('visible', models.BooleanField(default=True, verbose_name='Видимость')),
            ],
            options={
                'verbose_name': 'Категория сервиса',
                'verbose_name_plural': 'Сервисы - категории',
            },
        ),
    ]
