# Generated by Django 5.0.1 on 2024-03-03 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_userservices'),
        ('educationpart', '0003_studygroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='customperson',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_group_to_studygroup_id_fkey', to='educationpart.studygroup', verbose_name='Учебная группа'),
        ),
    ]
