# Generated by Django 5.0.1 on 2024-12-08 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0007_customperson_group'),
        ('reference', '0003_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceNotify',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('email', models.EmailField(
                    max_length=254,
                    verbose_name='Электронная почта'
                )),
                ('department', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='reference_notify_to_department_id_fkey',
                    to='college.department',
                    verbose_name='Площадка'
                )),
            ],
            options={
                'verbose_name': 'Оповещение',
                'verbose_name_plural': 'Настройка оповещений',
            },
        ),
    ]
