# Generated by Django 5.0.1 on 2024-02-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_couple'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
